### ISSUE TITLE
strange sqrt error with RHSs

### ISSUE THREAD

**Issue by dorugeber** [coneoproject/COFFEE#42] opened 2015-04-24 10:52 UTC
Using FFC's unkneecap_coffee with COFFEE's not_all_left_hand_sides,

```
from firedrake import *


mesh = UnitSquareMesh(4, 4)

V = FunctionSpace(mesh, "BDM", 1)
u0 = Function(V)
u0.assign(1.0)

Q = FunctionSpace(mesh, "DG", 0)

u = TrialFunction(Q)
v = TestFunction(Q)

f = Function(Q)
solve(u*v*dx == sqrt(dot(u0, u0))*v*dx, f)
```

fails with
```
<snip>
  File "/home/atm112/local/PyOP2/pyop2/host.py", line 58, in _ast_to_c
    ast_handler.plan_cpu(self._opts)
  File "/home/atm112/local/COFFEE/coffee/plan.py", line 415, in plan_cpu
    loop_opts = _generate_cpu_code(self, kernel, **params)
  File "/home/atm112/local/COFFEE/coffee/plan.py", line 245, in _generate_cpu_code
    loop_opt.rewrite(rewrite)
  File "/home/atm112/local/COFFEE/coffee/optimizer.py", line 109, in rewrite
    ew.expand()
  File "/home/atm112/local/COFFEE/coffee/rewriter.py", line 174, in expand
    ee.expand()
  File "/home/atm112/local/COFFEE/coffee/rewriter.py", line 659, in expand
    self._expand(self.stmt.children[1], self.stmt)
  File "/home/atm112/local/COFFEE/coffee/rewriter.py", line 605, in _expand
    return self._expand(node.children[0], node)
  File "/home/atm112/local/COFFEE/coffee/rewriter.py", line 610, in _expand
    l_node, l_type = self._expand(node.children[0], node)
  File "/home/atm112/local/COFFEE/coffee/rewriter.py", line 605, in _expand
    return self._expand(node.children[0], node)
  File "/home/atm112/local/COFFEE/coffee/rewriter.py", line 645, in _expand
    l_node, l_type = self._expand(node.children[0], node)
  File "/home/atm112/local/COFFEE/coffee/rewriter.py", line 605, in _expand
    return self._expand(node.children[0], node)
  File "/home/atm112/local/COFFEE/coffee/rewriter.py", line 628, in _expand
    raise RuntimeError("Expansion error: no symbol: %s" % sym.symbol)
RuntimeError: Expansion error: no symbol: FE1
```

Works if `sqrt(dot(u0, u0))` is just `dot(u0, u0)`.  Also works if the BDM space is changed to CG-n, with `sqrt(u0*u0)` or `sqrt(u0*u0*u0)`, etc.

**Comment by FabioLuporini** [comment] 2015-04-24 12:48
I'm trying it in the new branch support-more-exprs, which should be used together with pyop2.change-coffee-names and ffc.coffee-support-rhs, and seems to work

**Comment by dorugeber** [comment] 2015-04-24 13:04
Nice.  Would the fix be cherry-pickable, or would we have to wait for the entire branch to land?  (...I guess it breaks functionality elsewhere?)

**Comment by FabioLuporini** [comment] 2015-04-24 13:10
I think it's safer for the branch to land. Which shouldn't take much, since it's already passing all (firedrake regression + extrusion) tests. Actually, feel free to play with them; I'll run some other codes today to see everything is as expected.

This is the key branch to enable bendy (since it provides full support for 0 and 1 forms)

**Comment by dorugeber** [comment] 2015-04-24 13:10
Beautiful.

**Comment by FabioLuporini** [comment] 2015-05-06 12:05
Closing, since this is now fixed

**Closed by FabioLuporini** 2015-05-06 12:05 UTC
